
export { DetalleFuncionarioComponent } from './funcionarios/detalle-funcionario/detalle-funcionario.component';
export { PermissionsComponent } from './funcionarios/detalle-funcionario/permissions/permissions.component';
export { MenuChildComponent } from './funcionarios/detalle-funcionario/permissions/menu-child/menu-child.component';
export { SetFuncionarioComponent } from './funcionarios/detalle-funcionario/set-funcionario/set-funcionario.component';
export { CreateComponent } from './funcionarios/create/create.component';
export { DatosFuncionarioComponent } from './funcionarios/create/datos-funcionario/datos-funcionario.component';
export { InformacionEmpresaComponent } from './funcionarios/create/informacion-empresa/informacion-empresa.component';
export { PrestacionesSocialesComponent } from './funcionarios/create/prestaciones-sociales/prestaciones-sociales.component';
export { DotacionTallasComponent } from './funcionarios/create/dotacion-tallas/dotacion-tallas.component';
export { VerFuncionarioComponent } from './funcionarios/detalle-funcionario/ver-funcionario/ver-funcionario.component';
export { DatosBasicosComponent } from './funcionarios/detalle-funcionario/ver-funcionario/datos-basicos/datos-basicos.component';
export { SalarioComponent } from './funcionarios/detalle-funcionario/ver-funcionario/salario/salario.component';
export { DatosEmpresaComponent } from './funcionarios/detalle-funcionario/ver-funcionario/datos-empresa/datos-empresa.component';
export { AfiliacionesComponent } from './funcionarios/detalle-funcionario/ver-funcionario/afiliaciones/afiliaciones.component';
export { BonoComponent } from './funcionarios/detalle-funcionario/ver-funcionario/bono/bono.component';
export { CajaCompensacionComponent } from './caja-compensacion/caja-compensacion.component';
export { SedesComponent } from './sedes/sedes.component';
export { EpsComponent } from "./eps/eps.component";
// export { PersonsComponent } from './persons/persons.component';
// export { TableComponent } from './persons/table/table.component';
// export { ModalComponent } from './persons/modal/modal.component';
export { ModalCupComponent } from './cups/modal-cup/modal-cup.component';

export { ModalDatosBasicosComponent } from './funcionarios/detalle-funcionario/ver-funcionario/datos-basicos/modal-datos-basicos/modal-datos-basicos.component';
export { InformacionBaseRoutingModule } from './informacion-base-routing.module';
export { FuncionariosComponent } from './funcionarios/funcionarios.component';
// export { ProfesionalesComponent } from './profesionales/profesionales.component';
export { PacientesComponent } from './pacientes/pacientes.component';
export { EspecialidadesComponent } from './especialidades/especialidades.component';
export { CupsComponent } from './cups/cups.component';
export { RegimenesNivelesComponent } from './regimenes-niveles/regimenes-niveles.component';
export { AseguradorasComponent } from './aseguradoras/aseguradoras.component';
export { EmpresasComponent } from './empresas/empresas.component';
export { ProfessionalsModule } from './professionals/professionals.module';

export { EstructuraEmpresaComponent } from './estructura-empresa/estructura-empresa.component';
export { TurnosComponent } from './turnos/turnos.component';
export { TurnoFijoComponent } from './turnos/turno-fijo/turno-fijo.component';
export { CreateTurnoFijoComponent } from './turnos/turno-fijo/create-turno-fijo/create-turno-fijo.component';
export { TurnoRotativoComponent } from './turnos/turno-rotativo/turno-rotativo.component';
export { CreateTurnoRotativoComponent } from './turnos/turno-rotativo/create-turno-rotativo/create-turno-rotativo.component';
export { FondoPensionComponent } from './fondo-pension/fondo-pension.component';
export { ArlComponent } from './arl/arl.component';

export { FondoCesantiasComponent } from './fondo-cesantias/fondo-cesantias.component';
export { TaxisComponent } from './taxis/taxis.component';
export { HotelesComponent } from './hoteles/hoteles.component';
export { CiudadesComponent } from './ciudades/ciudades.component';
export { PaisesComponent } from './paises/paises.component';
export { LicenciaConduccionComponent } from './licencia-conduccion/licencia-conduccion.component';
